Feature/monitor register
0xD34DC0DE/ProjetIntegreTeam4 pull request #17
Opened 2021-09-30 22:10 UTC by wjeam

Added monitor registration, made some changed to the UX

2021-09-30 22:23 UTC, wjeam commented
In TopBar.js, I hardcoded the options for the dropdown menu at the top right. We will need to modify it eventually to make it easier to add more options. As of now, it is not a priority as we don't have many options.

2021-10-01 13:55 UTC, 0xD34DC0DE requested changes

2021-10-01 13:55 UTC, 0xD34DC0DE commented on backend/src/main/java/com/team4/backend/mapping/MonitorMapper.java
> +                .id(monitorDto.getId())
id coming from frontend shouldn't be trusted -> remove id mapping inside toEntity

2021-10-01 13:55 UTC, 0xD34DC0DE commented on backend/src/test/java/com/team4/backend/controller/MonitorControllerTest.java
> +                                    return s;
s stands for ??? (might want a m for monitor instead)

2021-10-01 13:55 UTC, 0xD34DC0DE commented on backend/src/test/java/com/team4/backend/mapping/MonitorMapperTest.java
> +        assertEquals(dto.getId(), entity.getId());
if you fix the dto -> entity id, you will need to change the assert here too

2021-10-01 13:55 UTC, 0xD34DC0DE commented on frontend/src/components/Content.js
> +};
Where are the child components going to be displayed ?
The content component should be a container (the content area) to the currently displayed work space.
See UserInfoStore for child component example.
Call me on discord for questions.

2021-10-01 15:13 UTC, 0xD34DC0DE approved these changes

2021-10-01 15:13 UTC, merged