Feature/monitor approve student internship
0xD34DC0DE/ProjetIntegreTeam4 pull request #57
Opened 2021-11-01 18:14 UTC by 0xD34DC0DE

Update develop to propagate changes

2021-11-02 21:28 UTC, ErwanDerrien requested changes

2021-11-03 02:16 UTC, 0xD34DC0DE commented on frontend/src/components/SignContractMonitorDialog.js
> +  const handleFormChange = (event) => {
va être utilisé dans le futur

2021-11-03 02:17 UTC, 0xD34DC0DE commented on backend/src/main/java/com/team4/backend/controller/PdfController.java
> +    @PreAuthorize("hasAnyAuthority('MONITOR', 'STUDENT')")
test controller, deleted the class

2021-11-03 02:26 UTC, ErwanDerrien approved these changes

2021-11-03 02:26 UTC, merged